services:
  manganotify:
    build: .
    container_name: manganotify

    # Map host → container ports (host port comes from .env, defaults to 8999)
    ports:
      - "${HOST_PORT:-8999}:8999"

    environment:
      # API base (can override if needed)
      MANGABAKA_BASE: ${MANGABAKA_BASE:-https://api.mangabaka.dev}

      # App port inside container (keep at 8999 unless you change app config)
      PORT: "8999"

      # Data dir used by server.py (watchlist lives here)
      DATA_DIR: /data

      # Poll interval in seconds (default 10 minutes)
      POLL_INTERVAL_SEC: ${POLL_INTERVAL_SEC:-600}

      # Optional: Pushover credentials
      PUSHOVER_USER_KEY: ${PUSHOVER_USER_KEY:-}
      PUSHOVER_APP_TOKEN: ${PUSHOVER_APP_TOKEN:-}

    volumes:
      - ./data:/data                # persist watchlist, logs, etc (must be writable)
      - ./static:/app/static:ro     # live-edit HTML/CSS/JS (read-only is fine)

    user: "${PUID:-1000}:${PGID:-1000}"

    restart: unless-stopped

    labels:
      net.unraid.docker.webui: "http://[IP]:[PORT:8999]/"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/gregoryn22/MangaNotify/refs/heads/master/manganotify_logo.png"
