version: "3.9"

services:
  manganotify:
    # If you publish an image, prefer this:
    # image: ghcr.io/gregoryn22/manganotify:latest
    build: .
    container_name: manganotify

    ports:
      - "${HOST_PORT:-8999}:8999"

    environment:
      MANGABAKA_BASE: ${MANGABAKA_BASE:-https://api.mangabaka.dev}
      PORT: "8999"
      DATA_DIR: /data
      POLL_INTERVAL_SEC: ${POLL_INTERVAL_SEC:-600}
      PUSHOVER_USER_KEY: ${PUSHOVER_USER_KEY:-}
      PUSHOVER_APP_TOKEN: ${PUSHOVER_APP_TOKEN:-}

    # Use a named volume so Docker owns perms correctly
    volumes:
      - manganotify-data:/data
      # optional live-edit (read-only is fine)
      - ./src/manganotify/static:/app/src/manganotify/static:ro

    # Let the image's default user (appuser, uid 10001) run the process
    # user:  <-- intentionally omitted

    restart: unless-stopped

    labels:
      net.unraid.docker.webui: "http://[IP]:[PORT:8999]/"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/gregoryn22/MangaNotify/refs/heads/master/images/manganotify_logo.png"

volumes:
  manganotify-data:
