version: "3.9"

services:
  manganotify:
    build: .
    container_name: manganotify

    # Map host → container ports (host port comes from .env, defaults to 8999)
    ports:
      - "${HOST_PORT:-8999}:8999"

    environment:
      # API base (can override if needed)
      MANGABAKA_BASE: ${MANGABAKA_BASE:-https://api.mangabaka.dev}

      # Flask/Gunicorn port inside container (keep at 8999 unless you change app config)
      PORT: "8999"

      # Optional: Pushover credentials
      PUSHOVER_USER_KEY: ${PUSHOVER_USER_KEY:-}
      PUSHOVER_APP_TOKEN: ${PUSHOVER_APP_TOKEN:-}

      # Watchlist location (inside container)
      WATCHLIST_FILE: ${WATCHLIST_FILE:-/data/watchlist.json}

      # Poll interval (minutes)
      WATCH_POLL_MINUTES: ${WATCH_POLL_MINUTES:-10}

    volumes:
      - ./data:/data                # persist watchlist, logs, etc
      - ./static:/app/static        # optional: live-edit HTML/CSS/JS
      - ./templates:/app/templates  # optional: override Jinja templates

    restart: unless-stopped

    labels:
      # Unraid-friendly labels (optional)
      net.unraid.docker.webui: "http://[IP]:[PORT:8999]/"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/gregoryn22/MangaNotify/refs/heads/master/manganotify_logo.png"
