services:
  manganotify:
    build: .
    container_name: manganotify
    ports:
      - "8999:8999"               # HOST:CONTAINER
    environment:
      # API base (defaults to https://api.mangabaka.dev if your code does that)
      MANGABAKA_BASE: "https://api.mangabaka.dev"
      # Flask/Gunicorn port inside container
      PORT: "8999"
      # Pushover (optional, uncomment below for use.
      # PUSHOVER_USER_KEY: "YOUR_PUSHOVER_USER_KEY_HERE"
      # PUSHOVER_APP_TOKEN: "YOUR_PUSHOVER_APP_TOKEN_HERE"
      # Where the app will save the watchlist
      WATCHLIST_FILE: "/data/watchlist.json"
    volumes:
      - ./data:/data              # persist watchlist, logs, etc
      - ./static:/app/static      # (optional) live-edit HTML/CSS/JS
      - ./templates:/app/templates # if using Jinja templates
    restart: unless-stopped
    # Unraid can infer WebUI from the template.
    # Adding the label helps Compose-managed stacks show a WebUI button:
    labels:
      net.unraid.docker.webui: "http://[IP]:[PORT:8999]/"
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/gregoryn22/MangaNotify/refs/heads/master/manganotify_logo.png'
