name: Publish Docker image (main)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Avoid piling up builds if you push multiple times quickly
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      # Change if your image name should differ from the repo name
      IMAGE_NAME: manganotify
      REGISTRY: ghcr.io
      # Owner is your GitHub org/user; yours is already lowercase (good for GHCR)
      OWNER: ${{ github.repository_owner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch emulation)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Generate OCI labels and tags:
      # - latest
      # - sha-<shortsha>
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and push (linux/amd64 + linux/arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Echo published tags
        run: |
          echo "Published tags:"
          echo "${{ steps.meta.outputs.tags }}"
          echo ""
          echo "Pull with:"
          echo "  docker pull ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest"
