name: Publish Docker image

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version
        id: v
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          echo "version=$TAG" >> $GITHUB_OUTPUT
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VCS_REF=${{ github.sha }}
            VERSION=${{ steps.v.outputs.version }}
            BUILD_DATE=${{ steps.meta.outputs.created }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/manganotify:${{ steps.v.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/manganotify:latest
